import os
from pathlib import Path

from openpilot.common.params import Params
from openpilot.system.hardware.hw import Paths

ENV_PATH = "/data/openpilot_server_env.sh"
DEFAULT_ATHENA_HOST = "wss://op.lirou.fun:666"
DEFAULT_API_HOST = "https://op.lirou.fun:666"
PERSIST_DONGLE_ID_PATH = Path(Paths.persist_root()) / "comma" / "dongle_id"


def _decode(val) -> str:
  if val is None:
    return ""
  if isinstance(val, bytes):
    return val.decode()
  return str(val)


def get_hosts(params: Params | None = None) -> tuple[str, str]:
  params = params or Params()
  athena = _decode(params.get("dp_athena_host")) or DEFAULT_ATHENA_HOST
  api = _decode(params.get("dp_api_host")) or DEFAULT_API_HOST
  return athena, api


def write_env_file(athena_host: str, api_host: str) -> None:
  content = (
    "#!/usr/bin/env bash\n"
    "# Generated by openpilot from DP panel settings. Do not edit while using DP config.\n"
    f"export ATHENA_HOST='{athena_host}'\n"
    f"export API_HOST='{api_host}'\n"
  )
  try:
    os.makedirs(os.path.dirname(ENV_PATH), exist_ok=True)
    with open(ENV_PATH, "w", encoding="utf-8") as f:
      f.write(content)
    os.chmod(ENV_PATH, 0o755)
  except OSError:
    pass


def clear_dongle_id_for_reregister(params: Params | None = None) -> None:
  params = params or Params()
  params.remove("DongleId")
  try:
    PERSIST_DONGLE_ID_PATH.unlink(missing_ok=True)
  except OSError:
    pass


def apply_from_params(params: Params | None = None) -> tuple[str, str]:
  athena_host, api_host = get_hosts(params)
  os.environ["ATHENA_HOST"] = athena_host
  os.environ["API_HOST"] = api_host
  write_env_file(athena_host, api_host)
  return athena_host, api_host
